/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Clients: () => import('#controllers/clients_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  Products: () => import('#controllers/products_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  Refunds: () => import('#controllers/refunds_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Users: () => import('#controllers/users_controller'),
}
